// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrB_vRgCUvZlOt_ZB3cvk-VEcFJAdbmA',
    appId: '1:613975336550:web:56f9825c93248cbdf3efa7',
    messagingSenderId: '613975336550',
    projectId: 'design-hub-ccdfc',
    authDomain: 'design-hub-ccdfc.firebaseapp.com',
    storageBucket: 'design-hub-ccdfc.firebasestorage.app',
    measurementId: 'G-6YVTSE1GZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC39dAxBCQW7UTM3oW5V1JRR8t80sPn4oA',
    appId: '1:613975336550:android:2dc72129d55c32caf3efa7',
    messagingSenderId: '613975336550',
    projectId: 'design-hub-ccdfc',
    storageBucket: 'design-hub-ccdfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgTpEcnYcjdfQmMpVVE_tQw2CjZCeqNVI',
    appId: '1:613975336550:ios:1f9df7ee200cc683f3efa7',
    messagingSenderId: '613975336550',
    projectId: 'design-hub-ccdfc',
    storageBucket: 'design-hub-ccdfc.firebasestorage.app',
    iosBundleId: 'com.example.designHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgTpEcnYcjdfQmMpVVE_tQw2CjZCeqNVI',
    appId: '1:613975336550:ios:1f9df7ee200cc683f3efa7',
    messagingSenderId: '613975336550',
    projectId: 'design-hub-ccdfc',
    storageBucket: 'design-hub-ccdfc.firebasestorage.app',
    iosBundleId: 'com.example.designHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZrB_vRgCUvZlOt_ZB3cvk-VEcFJAdbmA',
    appId: '1:613975336550:web:99edbe05cb9e55dbf3efa7',
    messagingSenderId: '613975336550',
    projectId: 'design-hub-ccdfc',
    authDomain: 'design-hub-ccdfc.firebaseapp.com',
    storageBucket: 'design-hub-ccdfc.firebasestorage.app',
    measurementId: 'G-HHEK0CJKHV',
  );
}
